[package]

name = "yaxpeax-pic17"
version = "0.0.1"
authors = [ "iximeow <me@iximeow.net>" ]
license = "0BSD"
repository = ""
description = """
A rust pic17 decoder
"""

[dependencies]
yaxpeax-arch = { path = "../../yaxpeax-arch" }

[[test]]
name = "test"
path = "test/test.rs"
